spring:
  application:
    name: mapfort-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rm-cn-9me49mca90004r8o.rwlb.rds.aliyuncs.com:5432/dataplatform
    username: yjy
    password: Yjy123456

server:
  port: 8081